export const WHATSAPP_URL = "https://wa.me/917499404640";
export const WHATSAPP_NUMBER = "+91 74994 04640";

export const categories = [
  {
    slug: "bakery",
    name: "Bakery & Patisserie",
    business: "Shivam Bakers",
    desc: "Artisan breads, cakes & pastries",
    icon: "🥐",
    accentColor: "#C8860A",
    bgPreview: "#0E0C08",
  },
  {
    slug: "salon",
    name: "Salon & Spa",
    business: "Bloom & Glow",
    desc: "Hair, skin & beauty services",
    icon: "✂",
    accentColor: "#E8A9C8",
    bgPreview: "#1A0F1A",
  },
  {
    slug: "restaurant",
    name: "Restaurant & Cafe",
    business: "The Spice Garden",
    desc: "Indian cuisine & dining",
    icon: "🍛",
    accentColor: "#E8760A",
    bgPreview: "#1C0F08",
  },
  {
    slug: "clinic",
    name: "Clinic & Healthcare",
    business: "Arogya Clinic",
    desc: "Trusted care for your family",
    icon: "🏥",
    accentColor: "#0E6670",
    bgPreview: "#0E6670",
  },
  {
    slug: "gym",
    name: "Gym & Fitness",
    business: "PowerZone Fitness",
    desc: "Memberships, classes & training",
    icon: "💪",
    accentColor: "#CCFF00",
    bgPreview: "#080808",
  },
  {
    slug: "realestate",
    name: "Real Estate",
    business: "Prestige Properties",
    desc: "Property listings & deals",
    icon: "🏠",
    accentColor: "#B87333",
    bgPreview: "#1C3144",
  },
];

export const pricingPlans = [
  {
    name: "Starter",
    subtitle: "Static Website",
    price: "₹8,999",
    duration: "one-time",
    color: "#15803D",
    features: [
      "Up to 5 pages",
      "Mobile responsive design",
      "Contact form",
      "WhatsApp integration",
      "1 year free hosting",
      "Basic on-page SEO",
      "Google Maps embed",
      "Social media links",
    ],
    cta: "Get Started",
    popular: false,
  },
  {
    name: "Business",
    subtitle: "Dynamic Website",
    price: "₹18,999",
    duration: "one-time",
    color: "#1C3144",
    features: [
      "Everything in Starter",
      "Admin panel (CMS)",
      "Blog / News section",
      "Photo gallery manager",
      "Google Analytics dashboard",
      "WhatsApp chat widget",
      "1 year hosting + support",
      "3 months free maintenance",
    ],
    cta: "Most Popular",
    popular: true,
  },
  {
    name: "E-Commerce",
    subtitle: "Online Store",
    price: "₹34,999",
    duration: "one-time",
    color: "#C8860A",
    features: [
      "Everything in Business",
      "Product catalog & categories",
      "Shopping cart",
      "UPI / Razorpay integration",
      "Order management system",
      "Inventory tracking",
      "Customer accounts",
      "Email notifications",
    ],
    cta: "Build My Store",
    popular: false,
  },
  {
    name: "Custom",
    subtitle: "Enterprise / App",
    price: "Contact us",
    duration: "",
    color: "#6B21A8",
    features: [
      "Multi-page web application",
      "Custom backend & database",
      "API integrations",
      "Advanced animations",
      "Performance optimization",
      "Security audit",
      "Priority support 24/7",
      "Dedicated project manager",
    ],
    cta: "Let's Talk",
    popular: false,
  },
];

export const addons = [
  { name: "Domain name", price: "₹999/year" },
  { name: "Extra pages", price: "₹1,500/page" },
  { name: "Logo design", price: "₹2,999" },
  { name: "SEO package", price: "₹2,999/month" },
  { name: "Monthly maintenance", price: "₹1,999/month" },
  { name: "Speed optimization", price: "₹3,999" },
];
